### ISSUE TITLE
Organize Afternoon Sessions

### ISSUE THREAD

**Issue by seantibor** [seantibor/EduSummit2023#2]

**Comment by ehmatthes** [comment]
Here's a [brief initial outline](https://github.com/seantibor/EduSummit2023/blob/ai_work_session/work_session_ai.md) of a work session that's a facilitated conversation about the impact of AI on teaching and learning Python.

This session didn't go through the usual application process, so I'm quite open to critiques/ suggestions.

**Comment by reuven** [comment]
@ehmatthes I love this outline. I'm really looking forward to this conversation; people keep asking me how I'll integrate ChatGPT into my courses, and I have a few ideas, but nothing concrete or truly useful.
